# Generated by Django 6.0.5 on 2026-05-10 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pontos', models.IntegerField(default=0)),
                ('jogos', models.IntegerField(default=0)),
                ('vitorias', models.IntegerField(default=0)),
                ('empates', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('gols_pro', models.IntegerField(default=0)),
                ('gols_contra', models.IntegerField(default=0)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonato.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada', models.IntegerField()),
                ('gols_mandante', models.IntegerField(blank=True, null=True)),
                ('gols_visitante', models.IntegerField(blank=True, null=True)),
                ('mandante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandante', to='campeonato.time')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to='campeonato.time')),
            ],
        ),
    ]
