# Generated by Django 6.0.5 on 2026-05-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='grupo',
            field=models.CharField(max_length=1),
        ),
        migrations.RemoveField(
            model_name='time',
            name='derrotas',
        ),
        migrations.RemoveField(
            model_name='time',
            name='empates',
        ),
        migrations.RemoveField(
            model_name='time',
            name='gols_contra',
        ),
        migrations.RemoveField(
            model_name='time',
            name='gols_pro',
        ),
        migrations.RemoveField(
            model_name='time',
            name='jogos',
        ),
        migrations.RemoveField(
            model_name='time',
            name='pontos',
        ),
        migrations.RemoveField(
            model_name='time',
            name='vitorias',
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
    ]
