# Generated by Django 6.0.5 on 2026-05-11 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0002_alter_time_grupo_remove_time_derrotas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='mandante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_casa', to='campeonato.time'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos_fora', to='campeonato.time'),
        ),
    ]
