# Generated by Django 6.0.5 on 2026-05-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0003_time_logo_alter_jogo_mandante_alter_jogo_visitante'),
    ]

    operations = [
        migrations.CreateModel(
            name='JogoMataMata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(max_length=50)),
                ('mandante', models.CharField(max_length=100)),
                ('visitante', models.CharField(max_length=100)),
                ('gols_mandante', models.IntegerField(blank=True, null=True)),
                ('gols_visitante', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
