# Generated by Django 6.0.5 on 2026-05-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0004_jogomatamata'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogomatamata',
            name='jogo_numero',
            field=models.IntegerField(default=1),
        ),
    ]
