# Generated by Django 6.0.5 on 2026-05-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0005_jogomatamata_jogo_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='divisao',
            field=models.CharField(choices=[('1', 'Primeira Divisão'), ('2', 'Segunda Divisão')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='time',
            name='divisao',
            field=models.CharField(choices=[('1', 'Primeira Divisão'), ('2', 'Segunda Divisão')], default='1', max_length=1),
        ),
    ]
