# Generated by Django 6.0.5 on 2026-05-13 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0006_jogo_divisao_time_divisao'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonato.jogo')),
            ],
        ),
    ]
