# Generated by Django 6.0.5 on 2026-05-13 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0007_eventopartida'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='ataque',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='time',
            name='defesa',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='time',
            name='meio_campo',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='eventopartida',
            name='descricao',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='time',
            name='grupo',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='EstatisticaPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posse_mandante', models.IntegerField(default=50)),
                ('posse_visitante', models.IntegerField(default=50)),
                ('finalizacoes_mandante', models.IntegerField(default=0)),
                ('finalizacoes_visitante', models.IntegerField(default=0)),
                ('finalizacoes_gol_mandante', models.IntegerField(default=0)),
                ('finalizacoes_gol_visitante', models.IntegerField(default=0)),
                ('escanteios_mandante', models.IntegerField(default=0)),
                ('escanteios_visitante', models.IntegerField(default=0)),
                ('faltas_mandante', models.IntegerField(default=0)),
                ('faltas_visitante', models.IntegerField(default=0)),
                ('amarelos_mandante', models.IntegerField(default=0)),
                ('amarelos_visitante', models.IntegerField(default=0)),
                ('vermelhos_mandante', models.IntegerField(default=0)),
                ('vermelhos_visitante', models.IntegerField(default=0)),
                ('penaltis_mandante', models.IntegerField(default=0)),
                ('penaltis_visitante', models.IntegerField(default=0)),
                ('jogo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to='campeonato.jogo')),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('posicao', models.CharField(choices=[('GOL', 'Goleiro'), ('DEF', 'Defensor'), ('MEI', 'Meio-campista'), ('ATA', 'Atacante')], max_length=3)),
                ('forca', models.IntegerField(default=50)),
                ('gols', models.IntegerField(default=0)),
                ('assistencias', models.IntegerField(default=0)),
                ('cartoes_amarelos', models.IntegerField(default=0)),
                ('cartoes_vermelhos', models.IntegerField(default=0)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campeonato.time')),
            ],
        ),
        migrations.AddField(
            model_name='eventopartida',
            name='jogador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campeonato.jogador'),
        ),
    ]
